#include "libft_tester.h"
#include "ft_tester.h"

const t_ftlist funct_list[] = {
	{"ft_strlen", test_ft_strlen},
	{"ft_strlcpy", test_ft_strlcpy},
	{"ft_strlcat", test_ft_strlcat},
	{"ft_strchr", test_ft_strchr},
	{"ft_strrchr", test_ft_strrchr},
	{"ft_strncmp", test_ft_strncmp},
	{"ft_strnstr", test_ft_strnstr},
	{"ft_memset", test_ft_memset},
	{"ft_memcpy", test_ft_memcpy},
	{"ft_memmove", test_ft_memmove},
	{"ft_memchr", test_ft_memchr},
	{"ft_memcmp", test_ft_memcmp},
	{"ft_strdup", test_ft_strdup},
	{"ft_bzero", test_ft_bzero},
	{"ft_isalpha", test_ft_isalpha},
	{"ft_isdigit", test_ft_isdigit},
	{"ft_isalnum", test_ft_isalnum},
	{"ft_isascii", test_ft_isascii},
	{"ft_isprint", test_ft_isprint},
	{"ft_toupper", test_ft_toupper},
	{"ft_tolower", test_ft_tolower},
	{"ft_atoi", test_ft_atoi},
	{"ft_calloc", test_ft_calloc},
	{"ft_substr", test_ft_substr},
	{"ft_strjoin", test_ft_strjoin},
	{"ft_strtrim", test_ft_strtrim},
	{"ft_split", test_ft_split},
	{"ft_itoa", test_ft_itoa},
	{"ft_strmapi", test_ft_strmapi},
	{"ft_striteri", test_ft_striteri},
	{"ft_putchar_fd", test_ft_putchar_fd},
	{"ft_putstr_fd", test_ft_putstr_fd},
	{"ft_putendl_fd", test_ft_putendl_fd},
	{"ft_putnbr_fd", test_ft_putnbr_fd},
	// {"ft_lstnew", test_ft_lstnew},
	// {"ft_lstadd_front", test_ft_lstadd_front},
	// {"ft_lstsize", test_ft_lstsize},
	// {"ft_lstlast", test_ft_lstlast},
	// {"ft_lstadd_back", test_ft_lstadd_back},
	// {"ft_lstdelone", test_ft_lstdelone},
	// {"ft_lstclear", test_ft_lstclear},
	// {"ft_lstiter", test_ft_lstiter},
	// {"ft_lstmap", test_ft_lstmap},
	{NULL, NULL}};
